### ISSUE TITLE
Show comments on certain page type only

### ISSUE THREAD

**Issue by micobarac** [silverstripe/silverstripe-comments#247]
I am using Silverstripe 4.1 and Blog module. I cannot find a way how to override comments.yml settings, in a way that Comments don't appear on Home page, About us and other pages but Blog post pages?

I tried overriding comments.yaml but Comments keep appearing on every page type.

Btw, documentation about configuring Comments module is very confusing:

```yml
enabled: true # Enables commenting to be disabled for a specific class (or subclass of a parent with commenting enabled)
enabled_cms: false # The 'enabled' option will be set via the CMS instead of config
```

Enables commenting to be disabled??? Hahahha. Cool stuff.

**Comment by andrewandante** [comment]
@micobarac you should be able to apply the `CommentsExtension` to `BlogPost` instead of `SiteTree` to ensure it only appears on `BlogPos`t pages - in addition, there is currently a bug raised in #242 about yaml configuration not behaving properly.

The `enabled_cms` flag means that there is a checkbox field per-page (I think, might be a global) that toggles whether comments are enabled.

**Comment by micobarac** [comment]
@andrewandante the problem is that that checkbox never appears in Settings...

**Comment by micobarac** [comment]
So, how do I circumvent the current yaml problem? What is the exact workaround? Can you share the steps, please? Thanks.

**Comment by andrewandante** [comment]
At the moment, you'll need to enable it directly against the CommentExtension as per this comment: https://github.com/silverstripe/silverstripe-comments/issues/242#issuecomment-378470738

**Comment by dhensby** [comment]
closing as duplicate

**Comment by ntd** [comment]
A bit late but... see #351 for a better way to do this on recent installations.
