### ISSUE TITLE
Implement comment threading

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-comments#28]
Technically not hugely challenging, more a UX issue. Comment form will likely need to be rethought out.

**Comment by tractorcow** [comment]
Also good to checkout is https://privacy.org.nz/blog/putting-the-fix-in/, which has a custom nested comments handler.

It would be really great if you could share a bit of your code with us, @gordonbanderson  :)

**Comment by gordonbanderson** [comment]
@tractorcow It's on my list, need to pull the threading page out of my theme and back into the module, testing it against the default Simple theme.

**Comment by gordonbanderson** [comment]
@tractorcow Not perfect due to somewhat fragmented coding time the last couple of days, but kind of working with the Simple theme https://github.com/gordonbanderson/silverstripe-comments/commits/THREADEDCOMMENTS

In mysite/_config.php add the following:
```
Commenting::set_config_value('SiteTree', 'use_gravatar', true);
Commenting::set_config_value('SiteTree', 'gravatar_size', 100);
Commenting::set_config_value('SiteTree', 'require_moderation', false);
Commenting::set_config_value('SiteTree', 'comments_per_page', 50);
Commenting::set_config_value('SiteTree', 'include_js', true);
Commenting::set_config_value('SiteTree','gravatar_default','mm');
Commenting::set_config_value('SiteTree', 'thread_comments', true);
Commenting::set_config_value('SiteTree', 'maximum_thread_comment_depth', 10);
Commenting::set_config_value('SiteTree', 'order_comments_by', 'Lineage');
```
I've added Lineage and Depth fields to Comment in order to load them quickly with no need for hierarchical traversal.

Known issues:
* CSS could do with a bit of a tidy up
* Config value maximum_thread_comment_depth needs checking in CanReply method of comment
* Requires JavaScript (this may be an issue given SilverStripe is used for NZ Govt sites, whose remit certainly used to be one of 'must work without JavaScript')
* I've dealt with the case of showing child comments when a parent comment is deleted (MarkedAsDeleted field of Comment), but realized when I was integrating my theme changes back in here that there is the outlying case of ad admin approving a comment where an ancestral comment has not been approved.  This of course would only happen if an admin replied to a comment that needed approval.
* Server side checks need done for the case where the Reply button is hidden in the interface.
* I had to change the value of RSSLinkPage to 'FIXME' in CommentingController, I still haven't had a chance to look at what is going no there.
* I've added tests for lineage and depth, but possibly some others are required.

**Comment by gordonbanderson** [comment]
* After cancelling or completing a reply the form and heading are out of order, ie the form is being added before instead of after the original heading.

**Comment by gordonbanderson** [comment]
Writing tests for CanReply() has proved fruitful:
* Take account of the disabled case, in that a disabled comment cannot be replied to.
* If a comment is not moderated, it cannot be replied to.  This helps mitigate with the problem of unapproved comments having approved children, but of course it is still possible for an admin to create that situation.

**Comment by gordonbanderson** [comment]
This is what I  have the comments looking like with the Simple theme now.
![test your site name](https://cloud.githubusercontent.com/assets/7060/5795332/45aeb07e-9fc0-11e4-8c94-1dd869e37c46.png)

In order to enable Twitter as part of the comments form and rendering add the following (or use extensions.yml)
```
Object::add_extension('Comment', 'CommentTwitterUsernameExtension');
Object::add_extension('CommentingController', 'CommentingControllerTwitterUsernameExtension');
```
In your page template Twitter needs initiated:
```
<script>window.twttr = (function (d, s, id) {
  var t, js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id; js.src= "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);
  return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } });
}(document, "script", "twitter-wjs"));
</script>
```

I've resolved most of the issues previously mentioned except the FIXME related to RSSLink.  Two outstanding JavaScript issues:
1) With moderation on multiple submission seems an issue, even though I disable the button.
2) Reply and action-links don't work in the unmoderated case where a new comment is immediately rendered upon submission.

**Comment by gordonbanderson** [comment]
@tractorcow Code pushed as requested

**Comment by gordonbanderson** [comment]
Remaining JavaScript issues fixed, scopre of the .on() method was incorrect.

**Comment by wilr** [comment]
PR welcome.

**Comment by gordonbanderson** [comment]
I'll aim to create a clean pull request tomorrow, namely remove console/error logging and rebase with cleaner commits.

**Comment by gordonbanderson** [comment]
A little later than planned, but pull request here https://github.com/silverstripe/silverstripe-comments/pull/93

**Comment by assertchris** [comment]
@tractorcow see this

**Comment by tractorcow** [comment]
Yeah I've been through this and I've had a look at @gordonbanderson's code. see https://github.com/silverstripe/silverstripe-comments/pull/94

I attempted to cleanup the code and get it ready to merge but i think it still needs work. The biggest problem i have with that implementation is the dependency on JS enabled. I would like to see, at least in the core module, a non-js compatible fallback.

**Comment by tractorcow** [comment]
I have come up with another solution to this at https://github.com/silverstripe/silverstripe-comments/pull/115 if you want to look at it, but without the reliance on JS (although it still uses js to enhance UX).

**Comment by gordonbanderson** [comment]
Late my time but I've finally had a chance to look at this, looks promising.  I've raised a pull request for a one character YML error in the configuration documentation, but I've just noticed that the configuration for nesting is missing from the documentation also.  But that should be a minor fix (for tomorrow!)

**Comment by tractorcow** [comment]
Nice thanks @gordonbanderson ! I suppose I can close this issue now?

**Comment by gordonbanderson** [comment]
Was about to close it but you've beaten me to it :)
